version: '3.9'

networks:
  traefik-proxy:
    name: traefik-proxy
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/traefik:/etc/traefik:ro
      - /etc/certificates:/etc/certificates:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true